import Head from 'next/head'
import Planner from '../components/Planner'

export default function Home() {
  return (
    <>
      <Head>
        <title>Raid CD Planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span style={{ display: "none", }}>
        {process.env['COMMIT_HASH']}
      </span>
      <Planner />
    </>
  )
}
